---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: docker-hub
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.clusterSecretStore.name }}

  target:
    name: docker-hub
    creationPolicy: Owner

  data:
    - secretKey: values
      remoteRef:
        key: docker-hub-credentials

    - secretKey: mypassword
      remoteRef:
        key: docker-hub-credentials
        property: password
  
  dataFrom:
    - extract:
        key: docker-hub-credentials
